#This means that whenever code is pushed to the main branch, this workflow will be executed.
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    container: node:17.6.0
    steps:
      - run: node --version
      - run: npm --version

    