#This means that whenever code is pushed to the main branch, this workflow will be executed.
on: push
jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:17.6.0
    steps:
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run tsc
      - run: cd client && npm install && npm run build && cd ..
      - run: npm run docker build -t tilitikki .
