on: push
jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:17.6.0
    steps:
      - uses: actions/checkout@v3
      - run: npm install
             npm run tsc:build
             cd client && npm install && npm run build && cd ..
             npm run docker build -t tilitikki .
